name: Auto Merge Main to Testing

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            token: ${{secret.ACTION_PAT}}
       
      - name: Configure Git
        run: |
          git config --global user.name 'Kalpana12-cmd'
          git config --global user.email 'kalpanag124@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrelated-histories
          git push origin testing